# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfdb607a13725c2773b399d6786b5487fac2dc0f431ae9561563f6a70c4b5a4fb35e0501af18f65eaa4bfe7081c750074fbeada7abd70e14a18b2a5ecdf2e538

test:
  secret_key_base: 91a4af2e808a03227783f610fb3fba3379cf79ccdbb19b2c22503fb56b29185f138114840fd27c4975bb2daf509c5a0ef80938d0ab48e7fa0bcf5b0fcf486dec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
